export const data = {
  name: "بیمارستان امیراعلم",
  subtitle: "بیمارستان تخصصی و فوق تخصصی",
  iconURL: "/images/hospital profile photo.png",
  address:
    "آدرس: تهران - تهران، بلوار شهران شمالی، بالاتر از فلکه دوم شهران، بعد از مسجد امام علی، ساختمان داروخانه شبانه روزی دکتر کریمان، طبقه سوم، بلوک شرقی، واحد 31",
  hours: "۲۴ ساعته",
  days: "همه روز",
  distance: "نزدیک من",
  appointmentKind: "گوش، حلق و بینی",
  specialServices: "جراحی پلاستیک و ترمیمی صورت زیبایی صورت و گردن",
  rating: 4.5,
  reviewsCount: 145,
  tags: [
    { label: "دولتی", type: "gov" },
    { label: "آموزشی", type: "edu" },
  ],
  phoneNumber: "3371771914-77881578",
  imageURLs: [
    "./images/clinic-img.jpg",
    "./images/clinic-img2.jpg",
    "./images/clinic-img.jpg",
    "./images/clinic-img2.jpg",
  ],
  description:
    "بیمارستان امیر اعلم تهران، یکی از قدیمی‌ترین و مجهزترین مراکز درمانی کشور، با بیش از 80 سال سابقه در ارائه خدمات پزشکی تخصصی و فوق‌تخصصی فعالیت می‌کند. این بیمارستان با دارا بودن بخش‌های پیشرفته‌ای همچون ENT، جراحی، داخلی، تصویربرداری و آزمایشگاه‌های دقیق، مرجع درمانی بسیاری از بیماران در سطح کشور است.",

  departments: [
    {
      title: "بخش جراحی و اتاق عمل",
      img: "/images/d3193b76d24e8b35680f63b2bf38b74fa1978adf.jpg",
      items: [
        "اتاق عمل جنرال",
        "اتاق عمل قلب",
        "اتاق عمل زنان",
        "لاپاراسکوپی",
        "توراکس",
      ],
    },
    {
      title: "بخش اورژانس",
      img: "/images/b373425746e13840b4c587631090171cc2b68b13.jpg",
      items: [
        "اتاق عمل جنرال",
        "اتاق عمل قلب",
        "اتاق عمل زنان",
        "لاپاراسکوپی",
        "توراکس",
      ],
    },
    {
      title: "بخش بستری",
      img: "/images/217f009c4b52403869a98f7861f127afe12a4efd.jpg",
      items: [
        "اتاق عمل جنرال",
        "اتاق عمل قلب",
        "اتاق عمل زنان",
        "لاپاراسکوپی",
        "توراکس",
      ],
    },
    {
      title: "بخش پزشکی هسته‌ای",
      img: "/images/961742c1484307906618e7fe8e410c1d4d5ac9b1.jpg",
      items: [
        "اتاق عمل جنرال",
        "اتاق عمل قلب",
        "اتاق عمل زنان",
        "لاپاراسکوپی",
        "توراکس",
      ],
    },
    {
      title: "بخش پرتونگاری و تصویربرداری",
      img: "/images/fe05cd718b453e228853ad1a7c0bca00f6909fca.jpg",
      items: [
        "اتاق عمل جنرال",
        "اتاق عمل قلب",
        "اتاق عمل زنان",
        "لاپاراسکوپی",
        "توراکس",
      ],
    },
    {
      title: "بخش آزمایشگاه و آسیب‌شناسی",
      img: "/images/f49d7e02c668788cf06af8a95d573ed0daefaf1b.jpg",
      items: [
        "اتاق عمل جنرال",
        "اتاق عمل قلب",
        "اتاق عمل زنان",
        "لاپاراسکوپی",
        "توراکس",
      ],
    },
  ],
  services: [
    "کلینیک درد ",
    "کلینیک ترک سیگار",
    "کلینیک روانشناسی سلامت ",
    "مرکز لیزر و زیبایی",
    "شنوایی سنجی",
    "ورزش بارداری، آمادگی زایمان و مراقبت از نوزاد",
    "مرکز لیزر و زیبایی",
    "شنوایی سنجی",
    "ورزش بارداری، آمادگی زایمان و مراقبت از نوزاد",
  ],
  specialists: [
    {
      name: "دکتر فروغ موحدزاده",
      image: "/images/doc.jpg",
      specialties: ["متخصص زنان و زایمان", "فلوشیپ نازایی"],
      raters: 145,
      rating: 4.5,
      tags: ["خوش برخورد", "وقت شناس"],
      days: ["شنبه", "دوشنبه"],
      hours: "8 تا 10",
      successfullAppointments: 625,
      hasAppointmentsThisWeek: false,
      closestAppointment: "شنبه 24/3 (13:30)",
    },
    {
      name: "دکتر فروغ موحدزاده",
      image: "/images/doc.jpg",
      specialties: ["متخصص زنان و زایمان", "فلوشیپ نازایی"],
      raters: 145,
      rating: 4.5,
      tags: ["خوش برخورد", "وقت شناس"],
      days: ["شنبه", "دوشنبه"],
      hours: "8 تا 10",
      successfullAppointments: 625,
      hasAppointmentsThisWeek: true,
      closestAppointment: "شنبه 24/3 (13:30)",
    },
    {
      name: "دکتر فروغ موحدزاده",
      image: "/images/doc.jpg",
      specialties: ["متخصص زنان و زایمان", "فلوشیپ نازایی"],
      raters: 145,
      rating: 4.5,
      tags: ["خوش برخورد", "وقت شناس"],
      days: ["شنبه", "دوشنبه"],
      hours: "8 تا 10",
      successfullAppointments: 625,
      hasAppointmentsThisWeek: true,
      closestAppointment: "شنبه 24/3 (13:30)",
    },
  ],
}

export const appointment = {
  kind: "نوبت متخصص زنان و زایمان",
  medicalCenter: {
    name: "نام مرکز درمانی",
    type: "نوع مرکز درمانی",
    img: "/images/hospital profile photo.png",
  },
  day: "شنبه 12 اردیبهشت",
  hour: "8 - 10",
  number: "شماره 13",
  address:
    "تهران - تهران، بلوار شهران شمالی، بالاتر از فلکه دوم شهران، بعد از مسجد امام علی، ساختمان داروخانه شبانه روزی دکتر کریمان، طبقه سوم، بلوک شرقی، واحد 31",
  doctor: {
    name: "دکتر فروغ موحدزاده",
    specialty: "متخصص زنان و زایمان",
    img: "/images/doc2.jpg",
  },
};